# ------------------------------------------------------------------------------
# encryption configuration generation
# ------------------------------------------------------------------------------

- include: encryption.yml

# ------------------------------------------------------------------------------
# kubeconfig generation
# ------------------------------------------------------------------------------

# kube-proxy configuration
# ------------------------------------------------------------------------------

- name: "configure cluster for kube-proxy"
  become: yes
  shell: |-
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ external_ip }}:6443 \
      --kubeconfig=kube-proxy.kubeconfig

      kubectl config set-credentials system:node:kube-proxy \
        --client-certificate=kube-proxy.pem \
        --client-key=kube-proxy-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-proxy.kubeconfig

      kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:node:kube-proxy \
        --kubeconfig=kube-proxy.kubeconfig

      kubectl config use-context default --kubeconfig=kube-proxy.kubeconfig
      chmod 0644 kube-proxy.kubeconfig
  args:
    chdir: /usr/share/ca-certificates/kthw

# nodes configuration
# ------------------------------------------------------------------------------

- include: node.yml
  loop: "{{ groups['nodes'] }}"
  loop_control:
    loop_var: node

# kube-controller-manager configuration
# ------------------------------------------------------------------------------

- name: "configure cluster for kube-controller-manager"
  become: yes
  shell: |-
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://127.0.0.1:6443 \
      --kubeconfig=kube-controller-manager.kubeconfig

      kubectl config set-credentials system:node:kube-controller-manager \
        --client-certificate=kube-controller-manager.pem \
        --client-key=kube-controller-manager-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-controller-manager.kubeconfig

      kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:node:kube-controller-manager \
        --kubeconfig=kube-controller-manager.kubeconfig

      kubectl config use-context default --kubeconfig=kube-controller-manager.kubeconfig
      chmod 0644 kube-controller-manager.kubeconfig
  args:
    chdir: /usr/share/ca-certificates/kthw


# kube-scheduler configuration
# ------------------------------------------------------------------------------

- name: "configure cluster for kube-scheduler"
  become: yes
  shell: |-
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://127.0.0.1:6443 \
      --kubeconfig=kube-scheduler.kubeconfig

      kubectl config set-credentials system:node:kube-scheduler \
        --client-certificate=kube-scheduler.pem \
        --client-key=kube-scheduler-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-scheduler.kubeconfig

      kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:node:kube-scheduler \
        --kubeconfig=kube-scheduler.kubeconfig

      kubectl config use-context default --kubeconfig=kube-scheduler.kubeconfig
      chmod 0644 kube-scheduler.kubeconfig
  args:
    chdir: /usr/share/ca-certificates/kthw

# admin configuration
# ------------------------------------------------------------------------------

- name: "configure cluster for admin"
  become: yes
  shell: |-
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://127.0.0.1:6443 \
      --kubeconfig=admin.kubeconfig

      kubectl config set-credentials system:node:admin \
        --client-certificate=admin.pem \
        --client-key=admin-key.pem \
        --embed-certs=true \
        --kubeconfig=admin.kubeconfig

      kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:node:admin \
        --kubeconfig=admin.kubeconfig

      kubectl config use-context default --kubeconfig=admin.kubeconfig
      chmod 0644 admin.kubeconfig
  args:
    chdir: /usr/share/ca-certificates/kthw

# ------------------------------------------------------------------------------
# copy configuration files to masters
# ------------------------------------------------------------------------------

- name: copy configuration files to masters
  delegate_to: "{{ item.0 }}"
  become: yes
  copy:
    src: "/usr/share/ca-certificates/kthw/{{ item.1 }}"
    dest: /root
    mode: 0600
  with_nested:
    - "{{ groups['masters'] }}"
    - "{{ pems }}"
  vars:
    pems:
      - admin.kubeconfig
      - kube-controller-manager.kubeconfig
      - kube-scheduler.kubeconfig
